DROP TABLE IF EXISTS bugs CASCADE;
CREATE TABLE bugs (
  name VARCHAR(255) NOT NULL,
  details VARCHAR(255) NOT NULL,
  steps VARCHAR(255) NOT NULL,
  version VARCHAR(255) NOT NULL,
  assigned INTEGER REFERENCES users(id) ON DELETE CASCADE,
  creator INTEGER REFERENCES users(id) ON DELETE CASCADE,
  priority_id INTEGER REFERENCES priorities(id) ON DELETE CASCADE,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  status_id INTEGER REFERENCES status(id) ON DELETE CASCADE
);